kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: write
    image: alpine
    commands:
      - echo "username=mix" > username

  - name: read
    image: alpine
    commands:
      - source username
      - echo $$username 
      
---
kind: pipeline
type: kubernetes
name: docker

steps:
- name: docker-login
  image: alpine
  environment:
    DOCKER_CONFIG: /root/.docker
  commands:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)\"}}}" > /root/.docker/config.json

---
kind: secret
name: docker_username
get:
  path: docker-login
  name: username
---
kind: secret
name: docker_password
get:
  path: docker-login
  name: password
