kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: write
    image: alpine
    commands:
      - echo "username=mix" > natthawut

  - name: read
    image: alpine
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - source username
      - echo $$username $username
      - echo $$USERNAME $USERNAME

---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
    - echo $$USERNAME
    - echo $PASSWORD

---
kind: secret
name: docker_username
get:
  path: docker-drone
  name: username
  
---
kind: secret
name: docker_password
get:
  path: docker-drone
  name: password
