kind: pipeline
type: kubernetes
name: default

# Define the steps to be executed in the pipeline
steps:
  - name: build
    image: node:14  # Specify the Docker image to use for this step
    commands:
      - npm install  # Example build commands

trigger:
  branch:
  - master
  event:
  - push
