kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: write
    image: alpine
    commands:
      - echo "username=mix" > username

  - name: read
    image: alpine
    commands:
      - source username
      - echo $$username 
