kind: pipeline
type: kubernetes
name: default

# Define the steps to be executed in the pipeline
steps:
  - name: build
    image: node:14  # Specify the Docker image to use for this step
    commands:
      - npm install  # Example build commands
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
        project-key: "nodejs"
        project-name: "nodejs"
        sonar.host.url: "https://sonarqube.tks.trueidc.com/"
        sonar.login: "sqp_2e39c6a0ff4c84d2355d061debeca8b59ccd7244"
trigger:
  branch:
  - main
  event:
  - push
