kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: API
    image: plugins/docker
    settings:
      repo: natthawutsae/api
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG#v}

  - name: apitotest
    image: natthawutsae/api
    detach: true
    ports:
      - 3000
  - name: run_integration_tests
    image: natthawutsae/api
    commands:
      - "npx cypress run --spec cypress/e2e/healthcheck.cy.js"
    depends_on:
      - apitotest