kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: write
    image: alpine
    commands:
      - echo "username=mix" > username

  - name: read
    image: alpine
    commands:
      - source username
      - echo $$username 
      
---
kind: pipeline
type: kubernetes
name: docker

steps:
- name: docker-login
  image: alpine
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - apk add --no-cache expect
    - echo "spawn docker login -u $DOCKER_USERNAME --password-stdin" > login.exp
    - echo "expect \Password: \" >> login.exp
    - echo "send \"$DOCKER_PASSWORD\\r\"" >> login.exp
    - echo "expect eof" >> login.exp
    - chmod +x login.exp
    - ./login.exp

---
kind: secret
name: docker_username
get:
  path: docker-login
  name: username
---
kind: secret
name: docker_password
get:
  path: docker-login
  name: password
