kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: set-variable
    image: alpine
    commands:
      - MY_VARIABLE="Hello, World!"
      - echo "Value of MY_VARIABLE is"
  # - name: use-variable
  #   image: alpine
  #   commands:
  #     - echo "Value of MY_VARIABLE in another step is: $MY_VARIABLE"

  # - name: apitotest
  #   image: natthawutsae/api
  #   detach: true
  #   ports:
  #     - 3000
  # - name: run_integration_tests
  #   image: natthawutsae/api
  #   commands:
  #     - "npx cypress run --spec cypress/e2e/healthcheck.cy.js"
  #   depends_on:
  #     - apitotest
