kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: docker
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
    - echo $PASSWORD | docker login -u $USERNAME --password-stdin

---
kind: secret
name: username
get:
  path: docker
  name: username

---
kind: secret
name: password
get:
  path: docker
  name: password
