kind: pipeline
type: kubernetes
name: default

# Define the steps to be executed in the pipeline
steps:
  - name: build
    image: node:14  # Specify the Docker image to use for this step
    commands:
      - npm install  # Example build commands
  steps:
    - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
        sonar_host: "https://sonarqube.tks.trueidc.com"
        sonar_token: "sqp_96384a4bc14d98fb7df2d324be5d601f86fcb461"
trigger:
  branch:
  - main
  event:
  - push
