kind: pipeline
type: docker
name: my-ci-pipeline

# Specify the trigger conditions for the pipeline
trigger:
  event:
    - push
    - pull_request

# Define the steps to be executed in the pipeline
steps:
  - name: build
    image: node:14  # Specify the Docker image to use for this step
    commands:
      - npm install  # Example build commands
