kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: write
    image: alpine
    commands:
      - echo "username=mix" > username

  - name: read
    image: alpine
    commands:
      - source username
      - echo $$username 
---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: docker
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
    - docker login -u $USERNAME -p $PASSWORD

---
kind: secret
name: username
get:
  path: docker
  name: username

---
kind: secret
name: password
get:
  path: docker
  name: password
