kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: write
    image: alpine
    commands:
      - echo "username=mix" > username

  - name: read
    image: alpine
    commands:
      - source username
      - echo $$username

  # - name: apitotest
  #   image: natthawutsae/api
  #   detach: true
  #   ports:
  #     - 3000
  # - name: run_integration_tests
  #   image: natthawutsae/api
  #   commands:
  #     - "npx cypress run --spec cypress/e2e/healthcheck.cy.js"
  #   depends_on:
  #     - apitotest
