kind: pipeline
type: kubernetes
name: default

# Define the steps to be executed in the pipeline
steps:
  - name: build
    image: node:14
    commands:
      - npm install
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
        sonar_host: "https://sonarqube.tks.trueidc.com"
        sonar_token:
          from_secret: sonar_token
trigger:
  branch:
  - main
  event:
  - push
