kind: pipeline
type: docker
name: nodejs-tests

# Define the trigger to specify when this pipeline should run.
trigger:
  branch:
    include:
      - main  # Change this to the branch you want to trigger the pipeline

# Define the container image with Node.js and other dependencies.
# Make sure to change the Node.js version as needed.
platform:
  os: linux
  arch: amd64
image: node:14

steps:
  - name: install_dependencies
    commands:
      - npm install

  - name: run_tests
    commands:
      - npm test
