kind: pipeline
type: kubernetes
name: default

# Define the steps to be executed in the pipeline
steps:
  - name: build
    image: node:14
    commands:
      - npm install
trigger:
  branch:
  - main
  event:
  - push
