kind: pipeline
type: kubernetes
name: MyApp

steps:
  - name: write
    image: alpine
    commands:
      - echo "username=mix" > username

  - name: read
    image: alpine
    commands:
      - source username
      - echo $$username 
      
---
kind: pipeline
type: kubernetes
name: docker

steps:
- name: build
  image: docker
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
    - docker login -u $USERNAME -p $PASSWORD

---
kind: secret
name: docker_username
get:
  path: docker-login
  name: username
  
---
kind: secret
name: docker_password
get:
  path: docker-login
  name: password
